steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bankruptcy-predictor', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bankruptcy-predictor']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bankruptcy-predictor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bankruptcy-predictor'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '1Gi'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/bankruptcy-predictor'